### PR TITLE
jwb edits

### PR DESCRIPTION
**Pull request by josephwb**
Here are my edits. Looks great. None of my edits were anything serious, although I was a bit of a fascist when it comes to 1) "data" being plural, and 2) use of the Oxford comma. :bowtie:

Feel free to disregard any and all edits, of course.

I also tested all of the code, and it all checks out.

### CODE REVIEW

**Comment by josephwb** [comment]
Crap. I don't know why i am 4 commits behind master; I did git pull before starting anything....

**Comment by josephwb** [comment]
Did I spend the whole morning editing the wrong manuscript version?

**Comment by dwinter** [comment]
Damn -- don't know what is about my last edits but @fmichonneau couldn't see them at first and seems you couldn't fetch them even after they were merged :grimacing: 

Hopefully the merge is not too painful, but you should definitely look closely at the changes I made, I'm sure I introduced crimes against oxford commas and data pluralization

**Comment by josephwb** [comment]
:poop::poop::poop::poop::poop::poop::poop: Yeah, I saw that Francois had a lag on your edits. 

Okay, I will go through the newer version. But I need to step away from this for a bit. I'll send in comments this evening.

**Comment by josephwb** [comment]
Deleting.

**Comment by dwinter** [comment]
Well that sucks. The only good news I can offer is that my edits (mostly this commit https://github.com/fmichonneau/rotl-ms/commit/26459fc5165132498bf038cbb43511ac756b69c8) only hit a couple of paragraphs, so it might be relatively easy to use your existing work.

**Pull request closed without merging**
